// <auto-generated />
using System;
using BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120072007_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BookAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Harper Lee",
                            Category = "Fiction",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8225261-L.jpg",
                            Language = "English",
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Category = "Dystopian",
                            ImageUrl = "https://covers.openlibrary.org/b/id/7222246-L.jpg",
                            Language = "English",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "F. Scott Fitzgerald",
                            Category = "Classic",
                            ImageUrl = "https://covers.openlibrary.org/b/id/7352160-L.jpg",
                            Language = "English",
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Category = "Romance",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8091016-L.jpg",
                            Language = "English",
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            Category = "Fantasy",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8101346-L.jpg",
                            Language = "English",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.D. Salinger",
                            Category = "Fiction",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231856-L.jpg",
                            Language = "English",
                            PublishedYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Herman Melville",
                            Category = "Adventure",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8100923-L.jpg",
                            Language = "English",
                            PublishedYear = 1851,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Leo Tolstoy",
                            Category = "Historical",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231852-L.jpg",
                            Language = "Russian",
                            PublishedYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.R.R. Tolkien",
                            Category = "Fantasy",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8235116-L.jpg",
                            Language = "English",
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Fyodor Dostoevsky",
                            Category = "Psychological",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8319781-L.jpg",
                            Language = "Russian",
                            PublishedYear = 1866,
                            Title = "Crime and Punishment"
                        });
                });

            modelBuilder.Entity("BookAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
